# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PetFinderProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PetFinderProject
pod 'Alamofire'
pod 'Gloss', '~> 3.2'
end
